[devshell]
name = "cake"

packages = [
  "agenix",
  "yj",
  "rage",
  "age-plugin-yubikey",
]

[[commands]]
package = "alejandra"
name = "alejandra"
help = "nix formatter"
category = "dev"

[[commands]]
package = "nix"
name = "nix flake check"
help = "evaluate flake attributes"
category = "test"

[[commands]]
package = "pixieboot"
name = "pixieboot"
help = "start pixiecore for automated network installation"
category = "bootstrap"

[[commands]]
package = "lint"
name = "lint"
help = "run a linter on all nix files"
category = "test"

[[commands]]
package = "cake-updaters"
name = "update-cargo-vendor-sha"
help = "update the cargo vendor sha of a rust package"
category = "updates"

[[commands]]
package = "cake-updaters"
name = "update-all-cargo-vendor-shas"
help = "update all cargo vendor shas of all rust packages"
category = "updates"

[[commands]]
package = "cake-updaters"
name = "update-fixed-output-derivation-sha"
help = "update the fixed output derivation sha of a package"
category = "updates"

[[commands]]
package = "cake-updaters"
name = "update-all-fixed-output-derivation-shas"
help = "update all fixed output derivation shas in all such packages"
category = "updates"
