system = "x86_64-linux"

[config]
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICcPgR1IDyaKKQECpqdoesNahtMWQYi2P0m0FoodPm5d"

profiles = [
  "profiles/hardware/intel",
  "profiles/acme",
  "profiles/unencrypted_fs",
  "profiles/hetzner_cloud",
  "profiles/k3s",
  "profiles/server",
  "profiles/state",
  "profiles/tailscale",
]

[config.users.groups.blazed]
gid = 1447

[config.users.users.blazed]
uid = 1447
hashedPassword = "$6$HST/IcrwobvqZd$8D7oml6RozVpXaAw/WjjcYJOfSd7HJ2DqC6jNrEBKs5bz7t0O7EgrYj33XBTcrAbOgsn3T2PS4ofd8S77Jc8X0"
openssh.authorizedKeys.keys = [
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7jrwDFcxP329CNp2kUlGH3cvvrY5DHTJdB6ZsjhpnK1yEVpRrG87TOkxrdBOX+s8bVL/8vR3xgvkaKl67zav9JG1xk9HOYKnAHJ7laLX0WJSHsdL9MHblUbVHnn7rXXQvzwmTUacQlF8h8LiTfGAcSNmj9hrehOzkU1v+mpeOsga7yAMuJWI1Tb7AJ+gzHO/72dEeA5VG0JC43KGMW4yYd12pG/58d9RkaT0Et/rXK7zpYhzaPSl1JlCxYYl12OcjQCoWTz5Bq5jS2cW5dup6/N6kuGdanTGxI4yUIWlUyLPjHUZ5g7EcyBuAE2/v33QUFiwhQjNvHdvhoaoil/T1hye2YJfZ6i+ghrN+jW4Prw2znZ+txRhFlIIXmeEMCBN4aLx5oTWH6qXHRGYjCSPhoU+P8jcagBKTApC0gzNK8jH4nJ8VhGs+g+N2337u5pjjCy9IAN9E8wiODgAvsButF+dFkHXEEzJ9pOrin4/MFUpVQklFwVTTCYP2mXa66zkI+JqoTNCkY5uJPxraxKdq0+0aWjh3KApr5vGA6ZFbkHX3tZdOAWTFZkM46Z3ZxohzWJfJg+eLyAmBbRjJjYU6X5lvb697aksAaqjV2NlkEBxmQTFf9QgrrzfTQubP1Nxj1wnrJd/ytofMIiVMVZ5JLAVIatetV9ZICmxF4j6Tiw== cardno:000606444817",
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDd9ZjCyGAjtjM6lCVZ46+c3PZvYDzFxECpa3NRwZG8zGnPcbIsFIyQzOdk0eywHFZikNeTxxxiDYXeTnuHuMkweVw5mYIwb8hXj8ts7qoCOVJP9P+KnnEb4WS/edG+Arv1nVeNIXswjHKjOtUSRtoNlRuY0x4kyF9EAbVTrHrB5HDtr7GTGQAGAEp33jQqHrIqFoWmNm9GQ3jqP0b4AcZVRXjAj+amqUQ2+gRt4r1r1kzLuvmOrTbOxnNB/N2hGNCkTbIqP1tDVq03EY0ISOWG+1+TW79ASkSYIdnmQBoB+x6Eh+9CGe65wjM0Op3Q564ZS3Qde1GzMchx5A4W7rrMAOzLXJaQ8Mi7gjsDjrqxBfDDXUU5JL5xn0PhhI1teXvQ5aR90cSs424PS3Yrbqs/pHsybcB/kh25MlO9rGXA9MHh7LlVCPIvus/SDopVgTgNIvhYbQh9xdogkG1XdkvyzXmvAJ6Gk/TR/KRWURwQyp1WJxJ8nHr/zUWrU55zXrN/5gWbDB5k9zuR5G4EGrZshM3EuNeQtjMlHcLWfoZuwaOmar/NOmaXzrBCZb/jXNhQkh6M94krXWE0DIkwsu+5n14llMo/OCxneIEqx4FqZePC8x8qpqfKRzSetOG5PVdCO/8w1erhkg8uETguiPTK4uCfCgtZ75ISpv+7nEwuQ== cardno:000607191648",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAICCghZ9Q+hC3hwCS8R6KdqQ8RefZgadLQUYC7upCejNCAAAABHNzaDo=",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIH8FItRsdPvpg8mTCF7gsKQJ4ABaOCE8a6PzamumRWe3AAAABHNzaDo=",
]

[config.age.secrets]
k3s-token  = { file = "secrets/k3s/token.age" }
argocd-vault-sercet = { file = "secrets/k3s/argocd-vault-secret.yaml.age", path = "/var/lib/rancher/k3s/server/manifests/argocd-vault-secret.yaml" }
argocd-cm = { file = "secrets/k3s/argocd-cm.yaml.age", path = "/var/lib/rancher/k3s/server/manifests/argocd-cm.yaml" }
argocd-repo-creds = { file = "secrets/k3s/argocd-repo-creds.yaml.age", path = "/var/lib/rancher/k3s/server/manifests/argocd-repo-creds.yaml" }
dex-env = { file = "secrets/dex-env.age" }
acme-cloudflare = { file = "secrets/acme-cloudflare.age" }

[config.networking.firewall]
allowedTCPPorts = [ 80, 443 ]

[config.services.dex]
enable = true
environmentFile = "/var/run/agenix/dex-env"

[config.services.dex.settings]
issuer = "https://id.internal.exsules.com"
oauth2.skipApprovalScreen = true
storage.type = "sqlite3"
storage.config.file = "/var/lib/dex/dex.db"
web.http = "127.0.0.1:5556"

[[config.services.dex.settings.connectors]]
id = "github"
name = "GitHub"
type = "github"
config.clientID = "$GITHUB_CLIENT_ID"
config.clientSecret = "$GITHUB_CLIENT_SECRET"
config.redirectURI = "https://id.internal.exsules.com/callback"
config.orgs = [ { name = "exsules", teams = [ "SRE", "Developers" ] } ]

[[config.services.dex.settings.staticClients]]
id = "k3s"
name = "k3s"
secretEnv = "DEX_K3S_CLIENT_SECRET"
redirectURIs = [ "http://localhost:8000" ]

[config.systemd.services.dex.serviceConfig]
BindPaths = [ "/var/lib/dex" ]

[config.services.nginx]
enable = true
recommendedTlsSettings = true
recommendedProxySettings = true
recommendedOptimisation = true
recommendedGzipSettings = true

[config.services.nginx.virtualHosts."id.internal.exsules.com"]
forceSSL = true
enableACME = true
locations."/".proxyPass = "http://127.0.0.1:5556"

[config.environment.state."/keep"]
directories = [
  "/var/lib/dex",
]

[config.services.k3s]
role = "server"
tokenFile = "/run/agenix/k3s-token"
after = [ "tailscaled.service" ]

[config.services.k3s.settings]
cluster-cidr = "10.244.0.0/16"
service-cidr = "10.96.0.0/12"
cluster-dns = "10.96.0.10"
node-ip = "$(get-iface-ip tailscale0)"
node-external-ip = "$(get-iface-ip eth0)"
advertise-address = "$(get-iface-ip tailscale0)"
flannel-iface = "tailscale0"
kube-controller-manager-arg.node-cidr-mask-size = 24
kube-apiserver-arg.oidc-issuer-url = "https://id.internal.exsules.com"
kube-apiserver-arg.oidc-username-claim = "email"
kube-apiserver-arg.oidc-groups-claim = "groups"
kube-apiserver-arg.oidc-client-id = "k3s"
node-label."svccontroller.k3s.cattle.io/enablelb" = "true"
node-label."topology.kubernetes.io/region" = "finland"
node-label."topology.kubernetes.io/zone" = "hetzner"
secrets-encryption = true
tls-san = ["angelica", "angelica.tailef5cf.ts.net"]

[config.services.k3s.autoDeploy]
kured = "pkg:kured-yaml/kured.yaml"
argocd = "pkg:argocd-yaml/argocd.yaml"

[config.services.k3s.autoDeploy.sre-project]
apiVersion = "argoproj.io/v1alpha1"
kind = "AppProject"
metadata.name = "sre"
metadata.namespace = "argocd"
finalizers = [ "resources-finalizer.argocd.argoproj.io" ]
spec.sourceRepos = [
  "https://github.com/exsules/gitops.git",
  "https://github.com/exsules/infra-helmfiles.git",
]
spec.clusterResourceWhitelist = [
  { group = "*", kind = "*" }
]
spec.destinations = [
  { namespace = "*", server = "https://kubernetes.default.svc" }
]
spec.namespaceResourceWhitelist = [
  { group = "*", kind = "*" }
]

[config.services.k3s.autoDeploy.exsules-project]
apiVersion = "argoproj.io/v1alpha1"
kind = "AppProject"
metadata.name = "exsules"
metadata.namespace = "argocd"
finalizers = [ "resources-finalizer.argocd.argoproj.io" ]
spec.sourceRepos = [ "https://github.com/exsules/gitops.git" ]
spec.clusterResourceWhitelist = [
  { group = "*", kind = "*" }
]
spec.destinations = [
  { namespace = "api-security", server = "https://kubernetes.default.svc" },
  { namespace = "exsules", server = "https://kubernetes.default.svc" }
]
spec.namespaceResourceWhitelist = [
  { group = "*", kind = "*" }
]

[config.services.k3s.autoDeploy.dex-gh-sre]
apiVersion = "rbac.authorization.k8s.io/v1"
kind = "ClusterRoleBinding"
metadata.name = "dex-gh-sre"
roleRef.apiGroup = "rbac.authorization.k8s.io"
roleRef.kind = "ClusterRole"
roleRef.name = "cluster-admin"
subjects = [
  { apiGroup = "rbac.authorization.k8s.io", kind = "Group", name = "exsules:SRE" }
]

[config.system.autoUpgrade]
enable = true
flake = "github:blazed/cake"
allowReboot = true
dates = "*:0/15"
randomizedDelaySec = "5min"
enableSentinel = true
