system = "x86_64-linux"

[config]

profiles = [
  "profiles/hardware/apu",
  "profiles/default_fs",
  "profiles/server",
  "profiles/state",
  "profiles/uuid_disk_crypt"
]

disk.dosLabel = true

[config.users.groups.blazed]
gid = 1447

[config.users.users.blazed]
uid = 1447
hashedPassword = "$6$a0SToZxEDl/7409g$w6YWLBRg7wLfxzFE1bLU8ysELUzthDmmtMvY7vbvTmlZmxDpv0eRrvpA3XUjPYiWuH.WlW/s/qdYjTzjByBcx/"
openssh.authorizedKeys.keys = [
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAICCghZ9Q+hC3hwCS8R6KdqQ8RefZgadLQUYC7upCejNCAAAABHNzaDo=",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAIH8FItRsdPvpg8mTCF7gsKQJ4ABaOCE8a6PzamumRWe3AAAABHNzaDo=",
]
