system = "x86_64-linux"

[config]
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMVQi0gFacHkXLTq4pdKHMrE2HF04EQ0SLJoNK4eMC0j"

profiles = [
  "profiles/hardware/nuc",
  "profiles/default_fs",
  "profiles/k3s",
  "profiles/server",
  "profiles/state",
  "profiles/uuid_disk_crypt",
  "profiles/wifi",
]

users.groups.blazed.gid = 1447
users.users.blazed.uid = 1447
users.users.blazed.hashedPassword = "$6$9vf795UF$6vX6MfqYBVyEx8byQIa4FO6ottr3MjK6M5GO6NwT54STXm9xBGKCe/iPcNgd0G3.p9Da4GnP3UYUZGitew2cw."
users.users.blazed.openssh.authorizedKeys.keys = [
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7jrwDFcxP329CNp2kUlGH3cvvrY5DHTJdB6ZsjhpnK1yEVpRrG87TOkxrdBOX+s8bVL/8vR3xgvkaKl67zav9JG1xk9HOYKnAHJ7laLX0WJSHsdL9MHblUbVHnn7rXXQvzwmTUacQlF8h8LiTfGAcSNmj9hrehOzkU1v+mpeOsga7yAMuJWI1Tb7AJ+gzHO/72dEeA5VG0JC43KGMW4yYd12pG/58d9RkaT0Et/rXK7zpYhzaPSl1JlCxYYl12OcjQCoWTz5Bq5jS2cW5dup6/N6kuGdanTGxI4yUIWlUyLPjHUZ5g7EcyBuAE2/v33QUFiwhQjNvHdvhoaoil/T1hye2YJfZ6i+ghrN+jW4Prw2znZ+txRhFlIIXmeEMCBN4aLx5oTWH6qXHRGYjCSPhoU+P8jcagBKTApC0gzNK8jH4nJ8VhGs+g+N2337u5pjjCy9IAN9E8wiODgAvsButF+dFkHXEEzJ9pOrin4/MFUpVQklFwVTTCYP2mXa66zkI+JqoTNCkY5uJPxraxKdq0+0aWjh3KApr5vGA6ZFbkHX3tZdOAWTFZkM46Z3ZxohzWJfJg+eLyAmBbRjJjYU6X5lvb697aksAaqjV2NlkEBxmQTFf9QgrrzfTQubP1Nxj1wnrJd/ytofMIiVMVZ5JLAVIatetV9ZICmxF4j6Tiw== cardno:000606444817",
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDd9ZjCyGAjtjM6lCVZ46+c3PZvYDzFxECpa3NRwZG8zGnPcbIsFIyQzOdk0eywHFZikNeTxxxiDYXeTnuHuMkweVw5mYIwb8hXj8ts7qoCOVJP9P+KnnEb4WS/edG+Arv1nVeNIXswjHKjOtUSRtoNlRuY0x4kyF9EAbVTrHrB5HDtr7GTGQAGAEp33jQqHrIqFoWmNm9GQ3jqP0b4AcZVRXjAj+amqUQ2+gRt4r1r1kzLuvmOrTbOxnNB/N2hGNCkTbIqP1tDVq03EY0ISOWG+1+TW79ASkSYIdnmQBoB+x6Eh+9CGe65wjM0Op3Q564ZS3Qde1GzMchx5A4W7rrMAOzLXJaQ8Mi7gjsDjrqxBfDDXUU5JL5xn0PhhI1teXvQ5aR90cSs424PS3Yrbqs/pHsybcB/kh25MlO9rGXA9MHh7LlVCPIvus/SDopVgTgNIvhYbQh9xdogkG1XdkvyzXmvAJ6Gk/TR/KRWURwQyp1WJxJ8nHr/zUWrU55zXrN/5gWbDB5k9zuR5G4EGrZshM3EuNeQtjMlHcLWfoZuwaOmar/NOmaXzrBCZb/jXNhQkh6M94krXWE0DIkwsu+5n14llMo/OCxneIEqx4FqZePC8x8qpqfKRzSetOG5PVdCO/8w1erhkg8uETguiPTK4uCfCgtZ75ISpv+7nEwuQ== cardno:000607191648",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAICCghZ9Q+hC3hwCS8R6KdqQ8RefZgadLQUYC7upCejNCAAAABHNzaDo="
]

age.secrets.k3s-token.file = "secrets/k3s/token.age"
age.secrets.wg-exsules.file = "secrets/elsa/wg-exsules.age"
age.secrets.wifi-networks.file = "secrets/wifi-networks.age"

networking.nat.enable = true
networking.nat.externalInterface = [ "wlan0" ]
networking.firewall.allowedUDPPorts = [ 51820 ]
networking.firewall.trustedInterfaces = [ "exsules" ]
networking.server-wireguard.enable = true
networking.server-wireguard.ips = [ "10.0.149.1/24" ]
networking.server-wireguard.listenPort = 51820
networking.server-wireguard.privateKeyFile = "/run/agenix/wg-exsules"
networking.server-wireguard.cidr = "10.0.149.0/22"
networking.server-wireguard.externalInterface =  "wlan0"
networking.server-wireguard.peers = [
  { publicKey = "7lUItjqmzF7Wwx4jvjqGO45uvkGiKmNQxx5DjXTiTDI=", allowedIPs = [ "10.0.149.2/32" ] },
  { publicKey = "sFiCyanPnKKhK5tL0L+l2ew0USq3BkU8SROv0oIQVA4=", allowedIPs = [ "10.0.149.3/32" ] },
  { publicKey = "qEKOiqpirwMHff9v0Du/34Vy2TXU2EchYlRyrZ/PsTk=", allowedIPs = [ "10.0.149.5/32" ] },
  { publicKey = "08ZvGL46b+TuMFO/ys8q6S3KADctaFitWLkyW+SUWRI=", allowedIPs = [ "10.0.149.6/32" ] },
  { publicKey = "HxUxKi3BGYEVwuwuT/R+eGCdFtl0hktbiewr93UL5lA=", allowedIPs = [ "10.0.149.20/32" ] },
  { publicKey = "LxGKvmlRmvgR/DVyzS6OYom/vj1JZdBQPhxUVjdn6HY=", allowedIPs = ["10.0.149.22/32" ] },
]

services.k3s.role = "agent"
services.k3s.tokenFile = "/run/agenix/k3s-token"
services.k3s.serverAddr = "https://10.0.149.5:6443"
services.k3s.settings.flannel-iface = "exsules"
services.k3s.settings.node-ip = "10.0.149.1"
services.k3s.settings.node-external-ip = "10.0.1.121"
services.k3s.after = [ "wireguard-exsules.service" ]
services.k3s.settings.secrets-encryption = true

system.autoUpgrade = { enable = false, flake = "github:blazed/cake", allowReboot = true, dates = "*:0/15", randomizedDelaySec = "5min", enableSentinel = true }
