system = "x86_64-linux"

[config]
publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEAjXIyhYMnnH2fJMA/Lr1JgZecxstafNSGHMe8UkIlc"

profiles = [
  "profiles/hardware/intel",
  "profiles/default_fs",
  "profiles/download_station",
  "profiles/nfs",
  "profiles/k3s",
  "profiles/server",
  "profiles/state",
  "profiles/uuid_disk_crypt",
]

users.groups.blazed.gid = 1447
users.users.blazed.uid = 1447
users.users.blazed.hashedPassword = "$6$BFjDwniRF8WnQq$Q8cYKd9ytsGQ1V64oi3fn1ePSJMwKvaQurcysyWd7TljnL.GuC4apfJDwAtAg6sDKIVYpYCSRlz7F6A592J.l0"
users.users.blazed.openssh.authorizedKeys.keys = [
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7jrwDFcxP329CNp2kUlGH3cvvrY5DHTJdB6ZsjhpnK1yEVpRrG87TOkxrdBOX+s8bVL/8vR3xgvkaKl67zav9JG1xk9HOYKnAHJ7laLX0WJSHsdL9MHblUbVHnn7rXXQvzwmTUacQlF8h8LiTfGAcSNmj9hrehOzkU1v+mpeOsga7yAMuJWI1Tb7AJ+gzHO/72dEeA5VG0JC43KGMW4yYd12pG/58d9RkaT0Et/rXK7zpYhzaPSl1JlCxYYl12OcjQCoWTz5Bq5jS2cW5dup6/N6kuGdanTGxI4yUIWlUyLPjHUZ5g7EcyBuAE2/v33QUFiwhQjNvHdvhoaoil/T1hye2YJfZ6i+ghrN+jW4Prw2znZ+txRhFlIIXmeEMCBN4aLx5oTWH6qXHRGYjCSPhoU+P8jcagBKTApC0gzNK8jH4nJ8VhGs+g+N2337u5pjjCy9IAN9E8wiODgAvsButF+dFkHXEEzJ9pOrin4/MFUpVQklFwVTTCYP2mXa66zkI+JqoTNCkY5uJPxraxKdq0+0aWjh3KApr5vGA6ZFbkHX3tZdOAWTFZkM46Z3ZxohzWJfJg+eLyAmBbRjJjYU6X5lvb697aksAaqjV2NlkEBxmQTFf9QgrrzfTQubP1Nxj1wnrJd/ytofMIiVMVZ5JLAVIatetV9ZICmxF4j6Tiw== cardno:000606444817",
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDd9ZjCyGAjtjM6lCVZ46+c3PZvYDzFxECpa3NRwZG8zGnPcbIsFIyQzOdk0eywHFZikNeTxxxiDYXeTnuHuMkweVw5mYIwb8hXj8ts7qoCOVJP9P+KnnEb4WS/edG+Arv1nVeNIXswjHKjOtUSRtoNlRuY0x4kyF9EAbVTrHrB5HDtr7GTGQAGAEp33jQqHrIqFoWmNm9GQ3jqP0b4AcZVRXjAj+amqUQ2+gRt4r1r1kzLuvmOrTbOxnNB/N2hGNCkTbIqP1tDVq03EY0ISOWG+1+TW79ASkSYIdnmQBoB+x6Eh+9CGe65wjM0Op3Q564ZS3Qde1GzMchx5A4W7rrMAOzLXJaQ8Mi7gjsDjrqxBfDDXUU5JL5xn0PhhI1teXvQ5aR90cSs424PS3Yrbqs/pHsybcB/kh25MlO9rGXA9MHh7LlVCPIvus/SDopVgTgNIvhYbQh9xdogkG1XdkvyzXmvAJ6Gk/TR/KRWURwQyp1WJxJ8nHr/zUWrU55zXrN/5gWbDB5k9zuR5G4EGrZshM3EuNeQtjMlHcLWfoZuwaOmar/NOmaXzrBCZb/jXNhQkh6M94krXWE0DIkwsu+5n14llMo/OCxneIEqx4FqZePC8x8qpqfKRzSetOG5PVdCO/8w1erhkg8uETguiPTK4uCfCgtZ75ISpv+7nEwuQ== cardno:000607191648",
  "sk-ssh-ed25519@openssh.com AAAAGnNrLXNzaC1lZDI1NTE5QG9wZW5zc2guY29tAAAAICCghZ9Q+hC3hwCS8R6KdqQ8RefZgadLQUYC7upCejNCAAAABHNzaDo="
]

age.secrets.k3s-token.file = "secrets/k3s/token.age"
age.secrets.wg-home.file = "secrets/sophia/wg-home.age"
age.secrets.wg-private.file = "secrets/sophia/wg-private.age"

boot.initrd.availableKernelModules = [
  "xhci_pci",
  "ahci",
  "mpt3sas",
  "usbhid",
  "usb_storage",
  "sd_mod",
]

networking.interfaces.eno1.useDHCP = true
networking.interfaces.eno2.useDHCP = false
networking.interfaces.eno3.useDHCP = false
networking.interfaces.eno4.useDHCP = false

networking.firewall.trustedInterfaces = [ "home" ]
networking.wireguard.enable = true
networking.wireguard.interfaces.home.ips = [ "10.0.149.20/32" ]
networking.wireguard.interfaces.home.privateKeyFile = "/run/agenix/wg-home"
networking.wireguard.interfaces.home.peers = [
  { publicKey = "S7cbuWJvDYznxAtbqOZyKvvC//fQuciKbOqpTV18Cx4=", allowedIPs = [ "10.0.149.0/24" ], endpoint = "10.0.1.121:51820", persistentKeepalive = 25 }
]

networking.private-wireguard.enable = true
networking.private-wireguard.ips = [
  "10.67.124.179/32",
  "fc00:bbbb:bbbb:bb01::4:7cb2/128",
]
networking.private-wireguard.privateKeyFile = "/run/agenix/wg-private"
networking.private-wireguard.peers = [
  { publicKey = "CYFNNfntzhRHn0+QHWv2eBOeU/sCZ5f6FLbTMUyIQHk=", allowedIPs = [ "0.0.0.0/0", "::0/0" ], endpoint = "185.204.1.219:51820", persistentKeepalive = 25 }
]

services.k3s.role = "agent"
services.k3s.tokenFile = "/run/agenix/k3s-token"
services.k3s.serverAddr = "https://10.0.149.5:6443"
services.k3s.settings.flannel-iface = "home"
services.k3s.settings.node-ip = "10.0.149.20"
services.k3s.settings.node-external-ip = "10.0.0.20"
services.k3s.after = [ "wireguard-home.service" ]

system.autoUpgrade = { enable = false, flake = "github:blazed/cake", allowReboot = true, dates = "*:0/15", randomizedDelaySec = "5min", enableSentinel = true }
