publicKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJYGuujsrO9pHLKD6uszuxZNQzOT1qV7GWKJM4Fz4Bjl"

profiles = [
  "profiles/default_fs",
  "profiles/nfs",
  "profiles/k3s",
  "profiles/server",
  "profiles/state",
  "profiles/download_station",
]

users.groups.blazed.gid = 1447
users.users.blazed.uid = 1447
users.users.blazed.hashedPassword = "$6$BFjDwniRF8WnQq$Q8cYKd9ytsGQ1V64oi3fn1ePSJMwKvaQurcysyWd7TljnL.GuC4apfJDwAtAg6sDKIVYpYCSRlz7F6A592J.l0"
users.users.blazed.openssh.authorizedKeys.keys = [
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7jrwDFcxP329CNp2kUlGH3cvvrY5DHTJdB6ZsjhpnK1yEVpRrG87TOkxrdBOX+s8bVL/8vR3xgvkaKl67zav9JG1xk9HOYKnAHJ7laLX0WJSHsdL9MHblUbVHnn7rXXQvzwmTUacQlF8h8LiTfGAcSNmj9hrehOzkU1v+mpeOsga7yAMuJWI1Tb7AJ+gzHO/72dEeA5VG0JC43KGMW4yYd12pG/58d9RkaT0Et/rXK7zpYhzaPSl1JlCxYYl12OcjQCoWTz5Bq5jS2cW5dup6/N6kuGdanTGxI4yUIWlUyLPjHUZ5g7EcyBuAE2/v33QUFiwhQjNvHdvhoaoil/T1hye2YJfZ6i+ghrN+jW4Prw2znZ+txRhFlIIXmeEMCBN4aLx5oTWH6qXHRGYjCSPhoU+P8jcagBKTApC0gzNK8jH4nJ8VhGs+g+N2337u5pjjCy9IAN9E8wiODgAvsButF+dFkHXEEzJ9pOrin4/MFUpVQklFwVTTCYP2mXa66zkI+JqoTNCkY5uJPxraxKdq0+0aWjh3KApr5vGA6ZFbkHX3tZdOAWTFZkM46Z3ZxohzWJfJg+eLyAmBbRjJjYU6X5lvb697aksAaqjV2NlkEBxmQTFf9QgrrzfTQubP1Nxj1wnrJd/ytofMIiVMVZ5JLAVIatetV9ZICmxF4j6Tiw== cardno:000606444817",
  "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDDd9ZjCyGAjtjM6lCVZ46+c3PZvYDzFxECpa3NRwZG8zGnPcbIsFIyQzOdk0eywHFZikNeTxxxiDYXeTnuHuMkweVw5mYIwb8hXj8ts7qoCOVJP9P+KnnEb4WS/edG+Arv1nVeNIXswjHKjOtUSRtoNlRuY0x4kyF9EAbVTrHrB5HDtr7GTGQAGAEp33jQqHrIqFoWmNm9GQ3jqP0b4AcZVRXjAj+amqUQ2+gRt4r1r1kzLuvmOrTbOxnNB/N2hGNCkTbIqP1tDVq03EY0ISOWG+1+TW79ASkSYIdnmQBoB+x6Eh+9CGe65wjM0Op3Q564ZS3Qde1GzMchx5A4W7rrMAOzLXJaQ8Mi7gjsDjrqxBfDDXUU5JL5xn0PhhI1teXvQ5aR90cSs424PS3Yrbqs/pHsybcB/kh25MlO9rGXA9MHh7LlVCPIvus/SDopVgTgNIvhYbQh9xdogkG1XdkvyzXmvAJ6Gk/TR/KRWURwQyp1WJxJ8nHr/zUWrU55zXrN/5gWbDB5k9zuR5G4EGrZshM3EuNeQtjMlHcLWfoZuwaOmar/NOmaXzrBCZb/jXNhQkh6M94krXWE0DIkwsu+5n14llMo/OCxneIEqx4FqZePC8x8qpqfKRzSetOG5PVdCO/8w1erhkg8uETguiPTK4uCfCgtZ75ISpv+7nEwuQ== cardno:000607191648",
]

age.secrets.k3s-token.file = "secrets/k3s/token.age"
age.secrets.wg-home.file = "secrets/sophia/wg-home.age"
age.secrets.wg-private.file = "secrets/sophia/wg-private.age"

networking.interfaces.eno1.useDHCP = true
networking.interfaces.eno2.useDHCP = false
networking.interfaces.eno3.useDHCP = false
networking.interfaces.eno4.useDHCP = false

networking.wireguard.enable = true
networking.wireguard.interfaces.home.ips = [ "10.0.149.20/32" ]
networking.wireguard.interfaces.home.privateKeyFile = "/run/secrets/wg-private"
networking.wireguard.interfaces.home.peers = [
  { publicKey = "JOrJsDXLKdAY+G6u7gh5cDwLZr+C0QrLv31K3vIJED8=", allowedIPs = [ "10.0.149.0/24" ], endpoint = "10.0.0.1:51820", persistentKeepalive = 25 }
]

networking.private-wireguard.ips = [
  "10.67.124.179/32",
  "fc00:bbbb:bbbb:bb01::4:7cb2/128",
]
networking.private-wireguard.privateKeyFile = "/run/secrets/wg-private"
networking.private-wireguard.peers = [
  { publicKey = "CYFNNfntzhRHn0+QHWv2eBOeU/sCZ5f6FLbTMUyIQHk=", allowedIPs = [ "0.0.0.0/0", "::0/0" ], endpoint = "185.204.1.219:51820", persistentKeepalive = 25 }
]

services.k3s.role = "server"
services.k3s.tokenFile = "/run/secrets/k3s-token"
services.k3s.clusterCIDR = "10.128.128.0/21"
services.k3s.serviceCIDR = "10.129.128.0/22"
services.k3s.clusterDNS = "10.129.128.10"
services.k3s.maxPodsPerNode = 30
services.k3s.nodeCIDRMaskSize = 26
services.k3s.after = [ "mnt-media.mount" ]

system.autoUpgrade = { enable = true, flake = "github:blazed/cake", allowReboot = true, dates = "*:0/15", randomizedDelaySec = "5min" }
