name: Nix Builder

on:
  pull_request: {}
  push:
    branches:
    - main

jobs:
  nix_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: |
        nix flake check

  create_package_matrix_x86_64_linux:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.job-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - id: job-matrix
      run: |
        echo "::set-output name=matrix::$(nix eval .#github-actions-package-matrix-x86-64-linux --json)"

  create_host_matrix_x86_64_linux:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.job-matrix.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - id: job-matrix
      run: |
        echo "::set-output name=matrix::$(nix eval .#github-actions-host-matrix-x86-64-linux --json)"

  build_package_x86_64_linux:
    needs: create_package_matrix_x86_64_linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{ fromJson(needs.create_package_matrix_x86_64_linux.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          substituters = https://nixpkgs-wayland.cachix.org https://nixpkgs.cachix.org https://nix-community.cachix.org https://blazed.cachix.org https://cachix.cachix.org https://cache.nixos.org/
          trusted-public-keys = nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= nixpkgs.cachix.org-1:q91R6hxbwFvDqTSDKwDAV4T5PxqXGxswD8vhONFMeOE= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= blazed.cachix.org-1:e9Rx3vtlQSp3nckCdGYpSFJbOb/hi1KuTyvWTBkiwAI= cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    - uses: cachix/cachix-action@v12
      if: ${{ matrix.pkg != 'pxebooter' }}
      with:
        name: blazed
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - env:
        PKG: ${{ matrix.pkg }}
      run: |
        nix build .#packages.x86_64-linux.$PKG -L

  build_host_x86_64_linux:
    needs: [create_host_matrix_x86_64_linux, build_package_x86_64_linux]
    runs-on: cake
    strategy:
      matrix: ${{ fromJson(needs.create_host_matrix_x86_64_linux.outputs.matrix) }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
          substituters = https://nixpkgs-wayland.cachix.org https://nixpkgs.cachix.org https://nix-community.cachix.org https://blazed.cachix.org https://cachix.cachix.org https://cache.nixos.org/
          trusted-public-keys = nixpkgs-wayland.cachix.org-1:3lwxaILxMRkVhehr5StQprHdEo4IrE8sRho9R9HOLYA= nixpkgs.cachix.org-1:q91R6hxbwFvDqTSDKwDAV4T5PxqXGxswD8vhONFMeOE= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= blazed.cachix.org-1:e9Rx3vtlQSp3nckCdGYpSFJbOb/hi1KuTyvWTBkiwAI= cachix.cachix.org-1:eWNHQldwUO7G2VkjpnjDbWwy4KQ/HNxht7H4SSoMckM= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
    - env:
        HOST: ${{ matrix.host }}
      run: |
        nix build .#nixosConfigurations.$HOST.config.system.build.toplevel -L

  summarize:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Build (matrix)
    needs: [build_package_x86_64_linux, build_host_x86_64_linux, nix_lint, nix_check]
    steps:
      - name: Check linting status
        if: ${{ needs.nix_lint.result != 'success' }}
        run: exit 1
      - name: Check flake check status
        if: ${{ needs.nix_check.result != 'success' }}
        run: exit 1
      - name: Check x86_64-linux package build matrix status
        if: ${{ needs.build_package_x86_64_linux.result != 'success' }}
        run: exit 1
      - name: Check host x86_64-linux build matrix status
        if: ${{ needs.build_host_x86_64_linux.result != 'success' }}
        run: exit 1
